spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.uri=mongodb://localhost:27017/chatting
spring.data.mongodb.uri=mongodb+srv://f20211732:krish123@cluster0.1j4pusn.mongodb.net/biddingdb?retryWrites=true&w=majority&appName=Cluster0 
#spring.jpa.hibernate.ddl-auto=update
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.web=DEBUG