spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.uri=mongodb://localhost:27017/chatting
spring.data.mongodb.uri=mongodb+srv://"Enter Your Credentials"
#spring.jpa.hibernate.ddl-auto=update
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.web=DEBUG